#BulPearl link : https://www.spigotmc.org/resources/93260/
#If you like the plugin, let a star on the Github repo https://github.com/AliHaine/BulPearl

damage: 2.0

can_kill: true

cooldown: 30

#[world1, world2, example3]
cooldown_blacklist_world: []

sound: LEVEL_UP

enable_craft_creator: true

messages:
  use_pearl: "&a[BulPearl] &aYou have used an enderpearl to teleport"
  on_cooldown: "&a[BulPearl] &cYou have to wait %time% before using again an EnderPearl"
  end_cooldown: "&a[BulPearl] &aYou can now use an enderpearl"
  craft_created: "&a[BulPearl] &aYou have created a craft for EnderPearl"
  reload: "&a[BulPearl] config reload"
  error_only_ingame: "&a[BulPearl] You can't use this command in the console"
  error_unknow: "&c[BulPearl] Unknow command"
  error_craft_creator_disable: "&c[BulPearl] The craft creator is disable in the config.yml"
  no_permission: "&c[BulPearl] you don't have the permission to reload the config"

actionbar:
  on_cooldown: "&cYou can reuse an enderpearl in &e%time%s"
  end_cooldown: "&aYou can now use again an EnderPearl"